# Generated by Django 5.0.2 on 2024-03-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(upload_to='book_cover')),
                ('published_date', models.DateTimeField()),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
