# Generated by Django 5.0.2 on 2024-07-12 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrowed_book',
            new_name='BorrowedBook',
        ),
        migrations.RenameModel(
            old_name='Borrowed_book_detail',
            new_name='BorrowedBookDetail',
        ),
    ]
