# Generated by Django 5.0.2 on 2024-07-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_borrowed_book_borrowedbook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(),
        ),
    ]
