# Generated by Django 5.0.2 on 2024-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_borrowedbook_librarian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbookdetail',
            name='returned',
            field=models.DateTimeField(null=True),
        ),
    ]
