# Generated by Django 5.0.2 on 2024-07-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_borrowedbookdetail_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='borrowedbookdetail',
            name='returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
